services:
  - type: web
    name: greenpilot-ml
    env: python
    plan: free
    buildCommand: "pip install -r app/requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
    envVars:
      - key: EM_API_TOKEN
        sync: false
    disk:
      name: csv-storage
      mountPath: /app/app
      sizeGB: 1
